const { jsPDF } = require('jspdf');
const { marked } = require('marked');
const fs = require('fs');
const path = require('path');

class PDFExportService {
  constructor() {
    this.setupMarked();
  }

  /**
   * Configure marked for better PDF output
   */
  setupMarked() {
    marked.setOptions({
      breaks: true,
      gfm: true,
      headerIds: false,
      mangle: false
    });
  }

  /**
   * Export document to PDF
   */
  async exportToPDF(documentData) {
    try {
      const {
        content,
        title,
        projectName,
        documentType,
        metadata = {}
      } = documentData;

      // Create new PDF document
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // Set up document properties
      doc.setProperties({
        title: title || `${projectName} - ${documentType}`,
        subject: `BMAD Method Document - ${documentType}`,
        author: 'BMAD Method System',
        creator: 'BMAD Method PDF Export',
        producer: 'BMAD Method Backend'
      });

      // Add document header
      this.addDocumentHeader(doc, {
        title: title || documentType,
        projectName,
        documentType,
        metadata
      });

      // Process markdown content
      const processedContent = this.preprocessMarkdown(content);
      
      // Convert markdown to structured content
      const sections = this.parseMarkdownSections(processedContent);
      
      // Add content to PDF
      let currentY = 40; // Start after header
      
      for (const section of sections) {
        currentY = this.addSectionToPDF(doc, section, currentY);
        
        // Check if we need a new page
        if (currentY > 250) { // Near bottom of page
          doc.addPage();
          currentY = 20;
        }
      }

      // Add footer to all pages
      this.addDocumentFooter(doc, {
        projectName,
        documentType,
        generatedAt: new Date().toISOString()
      });

      // Generate PDF buffer
      const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
      
      return {
        success: true,
        buffer: pdfBuffer,
        filename: this.generateFilename(projectName, documentType),
        size: pdfBuffer.length
      };

    } catch (error) {
      console.error('PDF Export Error:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Add document header
   */
  addDocumentHeader(doc, headerData) {
    const { title, projectName, documentType, metadata } = headerData;
    
    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 20, 20);
    
    // Project name
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Project: ${projectName}`, 20, 30);
    
    // Document type and date
    doc.setFontSize(10);
    doc.setTextColor(100);
    const dateStr = new Date().toLocaleDateString();
    doc.text(`${documentType} | Generated: ${dateStr}`, 20, 35);
    
    // Add separator line
    doc.setDrawColor(200);
    doc.line(20, 37, 190, 37);
    
    // Reset text color
    doc.setTextColor(0);
  }

  /**
   * Add document footer
   */
  addDocumentFooter(doc, footerData) {
    const { projectName, documentType, generatedAt } = footerData;
    const pageCount = doc.internal.getNumberOfPages();
    
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      
      // Footer line
      doc.setDrawColor(200);
      doc.line(20, 280, 190, 280);
      
      // Footer text
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text(`${projectName} - ${documentType}`, 20, 285);
      doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
      doc.text(`Generated by BMAD Method | ${new Date(generatedAt).toLocaleDateString()}`, 105, 290, { align: 'center' });
    }
  }

  /**
   * Preprocess markdown content
   */
  preprocessMarkdown(content) {
    // Remove metadata headers if present
    let processed = content.replace(/^---[\s\S]*?---\n/, '');
    
    // Handle Mermaid diagrams (convert to text description for now)
    processed = processed.replace(/```mermaid\n([\s\S]*?)\n```/g, (match, diagram) => {
      return `**Diagram:** ${diagram.split('\n')[0] || 'Flow diagram'}\n\n*[Diagram content would be rendered in web view]*\n`;
    });
    
    // Handle code blocks
    processed = processed.replace(/```(\w+)?\n([\s\S]*?)\n```/g, (match, lang, code) => {
      return `**Code Block${lang ? ` (${lang})` : ''}:**\n${code}\n`;
    });
    
    return processed;
  }

  /**
   * Parse markdown into sections
   */
  parseMarkdownSections(content) {
    const lines = content.split('\n');
    const sections = [];
    let currentSection = null;
    
    for (const line of lines) {
      // Check for headers
      const headerMatch = line.match(/^(#{1,6})\s+(.+)$/);
      if (headerMatch) {
        // Save previous section
        if (currentSection) {
          sections.push(currentSection);
        }
        
        // Start new section
        currentSection = {
          type: 'header',
          level: headerMatch[1].length,
          text: headerMatch[2],
          content: []
        };
      } else if (currentSection) {
        // Add content to current section
        currentSection.content.push(line);
      } else {
        // Content before first header
        if (!sections.length || sections[sections.length - 1].type !== 'content') {
          sections.push({
            type: 'content',
            content: [line]
          });
        } else {
          sections[sections.length - 1].content.push(line);
        }
      }
    }
    
    // Add final section
    if (currentSection) {
      sections.push(currentSection);
    }
    
    return sections;
  }

  /**
   * Add section to PDF
   */
  addSectionToPDF(doc, section, startY) {
    let currentY = startY;
    
    if (section.type === 'header') {
      // Add header
      const fontSize = Math.max(16 - (section.level * 2), 10);
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', 'bold');
      
      currentY += 5; // Add some space before header
      doc.text(section.text, 20, currentY);
      currentY += fontSize * 0.5; // Space after header
      
      // Add underline for main headers
      if (section.level <= 2) {
        doc.setDrawColor(150);
        doc.line(20, currentY, 190, currentY);
        currentY += 2;
      }
      
      // Process section content
      if (section.content && section.content.length > 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        currentY = this.addTextContent(doc, section.content.join('\n'), currentY + 3);
      }
    } else {
      // Add regular content
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      currentY = this.addTextContent(doc, section.content.join('\n'), currentY);
    }
    
    return currentY;
  }

  /**
   * Add text content with word wrapping
   */
  addTextContent(doc, text, startY) {
    if (!text.trim()) return startY + 5;
    
    const pageWidth = 170; // Available width (210 - 40 for margins)
    const lineHeight = 5;
    let currentY = startY;
    
    // Split text into paragraphs
    const paragraphs = text.split('\n\n');
    
    for (const paragraph of paragraphs) {
      if (!paragraph.trim()) continue;
      
      // Handle special formatting
      let processedParagraph = paragraph;
      let isBold = false;
      let isItalic = false;
      
      // Check for bold text
      if (processedParagraph.includes('**')) {
        isBold = true;
        processedParagraph = processedParagraph.replace(/\*\*(.*?)\*\*/g, '$1');
      }
      
      // Check for italic text
      if (processedParagraph.includes('*')) {
        isItalic = true;
        processedParagraph = processedParagraph.replace(/\*(.*?)\*/g, '$1');
      }
      
      // Set font style
      const fontStyle = isBold ? 'bold' : (isItalic ? 'italic' : 'normal');
      doc.setFont('helvetica', fontStyle);
      
      // Split long lines
      const lines = doc.splitTextToSize(processedParagraph, pageWidth);
      
      for (const line of lines) {
        if (currentY > 270) { // Near bottom of page
          doc.addPage();
          currentY = 20;
        }
        
        doc.text(line, 20, currentY);
        currentY += lineHeight;
      }
      
      currentY += 3; // Space between paragraphs
    }
    
    return currentY;
  }

  /**
   * Generate appropriate filename
   */
  generateFilename(projectName, documentType) {
    const sanitizedProject = (projectName || 'project')
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    
    const sanitizedType = (documentType || 'document')
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    
    const timestamp = new Date().toISOString().slice(0, 10);
    
    return `${sanitizedProject}-${sanitizedType}-${timestamp}.pdf`;
  }

  /**
   * Get document type mapping for better filenames
   */
  getDocumentTypeMapping() {
    return {
      'project-brief': 'project-brief',
      'prd': 'product-requirements',
      'architecture': 'architecture-document',
      'frontend-architecture': 'frontend-architecture',
      'style-guide': 'style-guide',
      'screen-inventory': 'screen-inventory',
      'component-specification': 'component-specifications',
      'uiux-specification': 'uiux-specification',
      'story': 'user-story'
    };
  }
}

module.exports = new PDFExportService();
